* Bump minimum NSS / NSPR version   - update debian/rules * Fix the profile migrator to not hang when ~/.mozilla doesn't exist, and   other improvements- update debian/migrator/xulapp-profilemigrator   - update debian/migrator/xulapp-profilemigrator * Build with --enable-startup-notification again, this got dropped   in the 3.6 => 4.0 update   - update debian/mozconfig.in * Ship the testpilot extension for beta as per the official builds, based   on the discussion on #developers. We achieve this by building with   --enable-update-channel=beta for the beta milestones only. The update   channel isn't used anywhere at runtime because we disable the updater.   This means that Ubuntu users can participate in testpilot user studies   in Natty   - update debian/rules   - update debian/firefox-core.install.in   - update debian/mozconfig.in * Add a hack to the launcher to handle being launched from an alternative,   which is a symlink to the launcher script, and breaks the current launch   mechanism. Also remove a useless stat() from the current script   - update debian/firefox.sh.in * Re-add patch that got dropped to not remove and re-add search plugins   during upgrade   - add debian/patches/bz534663_attXXX_normalize_distribution_searchplugins.patch   - update debian/patches/series

diff --git a/debian/firefox.sh.in b/debian/firefox.sh.in
--- a/debian/firefox.sh.in
+++ b/debian/firefox.sh.in
@@ -19,8 +19,10 @@ MOZ_APP_LAUNCHER=$NAME
 SERIES=@SERIES@
 BRAND="@STARTUP_WM_CLASS@"
 %%if DEB_MIN_SYSDEPS == 1
+FALLBACK_EXE=@APPNAME@-bin
 EXE="$APPNAME"-bin
 %%else
+FALLBACK_EXE=@APPNAME@
 EXE=$APPNAME
 %%endif
 # Hack for abrowser
@@ -29,15 +31,17 @@ PROFILENAME=`echo $APPNAME | sed -e 's/abrowser/firefox/'`
 export MOZ_APP_LAUNCHER
 unset UBUNTU_MENUPROXY
 
-while [ ! -x $LIBDIR/$EXE ] && [ -L "$NAME" ] ; do
-    NAME=`readlink -f $NAME`
-    LIBDIR=`dirname $NAME`
+while [ ! -x $LIBDIR/$EXE ] ; do
+    if [ -L "$NAME" ] ; then
+        NAME=`readlink -f $NAME`
+        LIBDIR=`dirname $NAME`
+    elif [ -x $LIBDIR/$FALLBACK_EXE ] ; then
+        EXE="$FALLBACK_EXE"
+    else
+       echo "Can't find $LIBDIR/$EXE"
+       exit 1
+    fi
 done
-
-if [ ! -x $LIBDIR/$EXE ] ; then
-	echo "Can't find $LIBDIR/$EXE"
-	exit 1
-fi
 
 usage () {
     $LIBDIR/$EXE -h | sed -e 's,/.*/,,'
