* Readd the debug hooks to the shell wrapper script   - update debian/firefox.sh.in

diff --git a/debian/firefox.sh.in b/debian/firefox.sh.in
--- a/debian/firefox.sh.in
+++ b/debian/firefox.sh.in
@@ -30,6 +30,56 @@ while [ ! -x $MOZ_LIBDIR/$MOZ_APP_NAME ] ; do
     fi
 done
 
+usage () {
+    $MOZ_LIBDIR/$MOZ_APP_NAME -h | sed -e 's,/.*/,,'
+    echo
+    echo "      -g or --debug          Start within debugger"
+    echo "      -d or --debugger       Specify debugger to start with (eg, gdb or valgrind)"
+    echo "      -a or --debugger-args  Specify arguments for debugger"
+}
+
+moz_debug=0
+moz_debugger_args=""
+moz_debugger="gdb"
+
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -h | --help )
+            usage
+            exit 0
+            ;;
+        -g | --debug )
+            moz_debug=1
+            shift
+            ;;
+        -d | --debugger)
+            moz_debugger=$2;
+            if [ "${moz_debugger}" != "" ]; then
+	      shift 2
+            else
+              echo "-d requires an argument"
+              exit 1
+            fi
+            ;;
+        -a | --debugger-args )
+            moz_debugger_args=$2;
+            if [ "${moz_debugger_args}" != "" ] ; then
+                shift 2
+            else
+                echo "-a requires an argument"
+                exit 1
+            fi
+            ;;
+        -- ) # Stop option processing
+            shift
+            break
+            ;;
+        * )
+            break
+            ;;
+    esac
+done
+
 %%if MOZ_APP_NAME != MOZ_APP_BASENAME
 if [ $MOZ_APP_NAME != $MOZ_APP_BASENAME ] &&
    [ ! -e ${HOME}/${MOZ_PROFILE_PREFIX}${MOZ_APP_NAME} ] &&
@@ -38,4 +88,24 @@ if [ $MOZ_APP_NAME != $MOZ_APP_BASENAME ] &&
 fi
 %%endif
 
-exec $MOZ_LIBDIR/$MOZ_APP_NAME "$@"
+if [ $moz_debug -eq 1 ] ; then
+    debugger=`which $moz_debugger`
+    if [ ! -x $debugger ] ; then
+       echo "Invalid debugger"
+       exit 1
+    fi
+
+    case `basename $debugger` in
+       gdb)
+         exec $debugger $moz_debugger_args --args $MOZ_LIBDIR/$MOZ_APP_NAME "$@"
+         ;;
+       valgrind)
+         exec $debugger $moz_debugger_args $MOZ_LIBDIR/$MOZ_APP_NAME "$@"
+         ;;
+       *)
+         exec $debugger $moz_debugger_args $MOZ_LIBDIR/$MOZ_APP_NAME "$@"
+         ;;
+    esac
+else
+    exec $MOZ_LIBDIR/$MOZ_APP_NAME "$@"
+fi
