* Set up alternatives in the postinst script on abort-remove   - update debian/firefox.postinst.in * Add maintainer script magic for moving the system pref file   - update debian/firefox.postinst.in   - update debian/firefox.postrm.in   - update debian/firefox.preinst.in * Only run the Apparmor stuff in the postinst script on configure, and   in the preinst script on install or upgrade   - update debian/firefox.postinst.in   - update debian/firefox.preinst.in

diff --git a/debian/firefox.postinst.in b/debian/firefox.postinst.in
--- a/debian/firefox.postinst.in
+++ b/debian/firefox.postinst.in
@@ -5,7 +5,21 @@ set -e
 MOZ_LIBDIR=@MOZ_LIBDIR@
 MOZ_APP_NAME=@MOZ_APP_NAME@
 
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
+# Move a conffile without triggering a dpkg question
+finish_mv_conffile() {
+    local OLDCONFFILE="$1"
+    local NEWCONFFILE="$2"
+
+    rm -f $OLDCONFFILE.dpkg-remove
+
+    [ -e "$OLDCONFFILE" ] || return 0
+
+    echo "Preserving user changes to $NEWCONFFILE (renamed from $OLDCONFFILE)..."
+    mv -f "$NEWCONFFILE" "$NEWCONFFILE.dpkg-new"
+    mv -f "$OLDCONFFILE" "$NEWCONFFILE"
+}
+
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ] ; then
     if [ `dpkg-divert --truename /usr/bin/$MOZ_APP_NAME` != "/usr/bin/$MOZ_APP_NAME" ] ; then
         # Ubuntuzilla has trashed this install. Grrrrrrrrrr!
         BROKEN=1
@@ -38,7 +52,9 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
             echo "/usr/bin/$MOZ_APP_NAME has been diverted by $PACKAGE"
         fi
     fi
+fi
 
+if [ "$1" = "configure" ] ; then
     #
     # AppArmor
     #
@@ -100,8 +116,9 @@ EOM
     #
     # End AppArmor
     #
-fi
 
+    finish_mv_conffile "/etc/${MOZ_APP_NAME}/pref/firefox.js" "/etc/${MOZ_APP_NAME}/syspref.js"
+fi
 echo "Please restart all running instances of $MOZ_APP_NAME, or you will experience problems."
 
 if [ -d /var/run ] ; then
