* Replace the old profile migrator. The previous one relied on hard-coded   values and fragile shell script that isn't really scalable enough   now that stable Ubuntu releases see new major Firefox versions. The   new profile migrator doesn't require any hard-coded values, and should   be lower maintenance   - add debian/migrator/xulapp-profilemigrator   - remove debian/migrator/main.c   - update debian/rules   - update debian/firefox.sh.in   - update debian/firefox.install.pp   - update debian/control

diff --git a/debian/firefox.sh.in b/debian/firefox.sh.in
--- a/debian/firefox.sh.in
+++ b/debian/firefox.sh.in
@@ -13,18 +13,24 @@
 MOZDIR=$HOME/.mozilla
 LIBDIR=@DEB_CONFIGURE_LIBEXECDIR@
 GDB=/usr/bin/gdb
-NAME=`which $NAME`
+NAME=`which $0`
 APPNAME=`basename $NAME`
 MOZ_APP_LAUNCHER=$NAME
 SERIES=@SERIES@
+BRAND=@BRAND_NAME@
 
 export MOZ_APP_LAUNCHER
 unset UBUNTU_MENUPROXY
 
-while [ ! -x "$LIBDIR/$APPNAME"-bin ] && [ -L "$NAME" ]; do
+while [ ! -x "$LIBDIR/$APPNAME"-bin ] && [ -L "$NAME" ] ; do
     NAME=`readlink -f $NAME`
     LIBDIR=`dirname $NAME`
 done
+
+if [ ! -x "$LIBDIR/$APPNAME"-bin ] ; then
+	echo "Can't find $LIBDIR/$APPNAME-bin"
+	exit 1
+fi
 
 usage () {
     $LIBDIR/$APPNAME -h | sed -e 's,/.*/,,'
@@ -66,16 +72,16 @@ done
 
 if [ -x $LIBDIR/xulapp-profilemigrator ] ; then
     if [ ! -d $MOZDIR/$APPNAME ] ; then
-        $LIBDIR/xulapp-profilemigrator -s $SERIES -p $MOZDIR/$APPNAME
-    elif [ -f $MOZDIR/$APPNAME.last-series ] ; then
-        last_series="$(cat $MOZDIR/APPNAME.last-series)"
-        if [ $SERIES -gt $last_series ] ; then
-            $LIBDIR/xulapp-profilemigrator -s $SERIES -p $MOZDIR/$APPNAME
+        $LIBDIR/xulapp-profilemigrator -s $SERIES -p $MOZDIR/$APPNAME -b $BRAND
+    elif [ -f $MOZDIR/$APPNAME.series-stamp ] ; then
+        last_series=`cat $MOZDIR/$APPNAME.series-stamp`
+        if [ $SERIES != $last_series ] ; then
+            $LIBDIR/xulapp-profilemigrator -s $SERIES -p $MOZDIR/$APPNAME -b $BRAND
         fi
+    else
+	$LIBDIR/xulapp-profilemigrator -s $SERIES -p $MOZDIR/$APPNAME -b $BRAND
     fi
 fi
-
-echo $SERIES >> $MOZDIR/$APPNAME.last-series
 
 LD_LIBRARY_PATH=${LIBDIR}:${LIBDIR}/plugins${LD_LIBRARY_PATH:+":$LD_LIBRARY_PATH"}
 export LD_LIBRARY_PATH
