Ensure we fail if some language packs are removed. Also warn if we can't use a locale because we don't have a description for it

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -502,6 +502,10 @@ refresh-supported-languages: apply-patches
 					fi \
 				done < $(LANGPACK_O_MATIC)/maps/languages ; \
 			fi ; \
+			if [ -z "$$desc" ] ; \
+			then \
+				skipped="$$skipped $$language" ; \
+			fi ; \
 			if [ "$$blacklist" = "0" ] && [ ! -z "$$desc" ] && [ -f $(DEB_BUILDDIR)/l10n/$${language}/toolkit/defines.inc ] ; \
 			then \
 				echo "$$language" >> debian/locales-supported ; \
@@ -515,7 +519,40 @@ refresh-supported-languages: apply-patches
 				fi \
 			fi \
 		fi \
-	done < $(DEB_BUILDDIR)/browser/locales/shipped-locales
+	done < $(DEB_BUILDDIR)/browser/locales/shipped-locales ; \
+	if [ ! -z "$$skipped" ] ; \
+	then \
+		echo "" ; \
+		echo "These locales could be built but we have no description from them:" $$skipped ; \
+		echo "" ; \
+	fi
+
+	has_missing=0 ; \
+	while read oldline ; \
+	do \
+		found=0 ; \
+		while read newline ; \
+		do \
+			if [ "$$oldline" = "$$newline" ] ; \
+			then \
+				found=1 ; \
+			fi \
+		done < debian/locales-supported ; \
+		if [ $$found = 0 ] ; \
+		then \
+			if [ $$has_missing = 0 ] ; \
+			then \
+				echo "*** SOME LOCALES ARE MISSING ***" ; \
+				has_missing=1 ; \
+			fi ; \
+			echo "Missing locale" $$oldline ; \
+		fi \
+	done < debian/locales-supported.old ; \
+	if [ $$has_missing = 1 ] && [ -z $(IGNORE_MISSING) ] ; \
+	then \
+		mv debian/locales-supported.old debian/locales-supported ; \
+		exit 1 ; \
+	fi
 
 	rm -f debian/locales-supported.old
 
